### ISSUE TITLE
About contact annotations

### ISSUE THREAD

**Issue by tghim** [jnnan/trumans_utils#10]
First of all, thank you for sharing your wonderful work.

I have two questions. 

First, I am curious about how the contact annotation is stored. I looked through the dataset you shared, but I am not sure where the contact annotation is.

Second, I am curious whether there is contact annotation for human-scene as well as human-object contact. In Supplemental Figure A4, I can see that there is ground contact label, but I am not sure if there are contact labels for other scenes.

I would greatly appreciate it if you could answer.

**Comment by anonymous240829** [comment]
The contact annotation used for the experiments is stored as (0, 1) label for each vertex of the human mesh. Since we have converted the scenes and objects as watertight meshes, the contact-related annotation can be directly generated by Signed Distance Function using Kaolin library (https://kaolin.readthedocs.io/en/latest/modules/kaolin.metrics.trianglemesh.html)
kaolin.metrics.trianglemesh.point_to_mesh_distance

**Comment by jnnan** [comment]
The contact annotation used for the experiments is stored as (0, 1) label for each vertex of the human mesh. Since we have converted the scenes and objects as watertight meshes, the contact-related annotation can be directly generated by Signed Distance Function using Kaolin library (https://kaolin.readthedocs.io/en/latest/modules/kaolin.metrics.trianglemesh.html)
kaolin.metrics.trianglemesh.point_to_mesh_distance

**Comment by tghim** [comment]
So, objects and scenes, unlike humans, do not have labels for contact?

**Comment by jnnan** [comment]
Contact map on objects and scenes can obtain similarly using Kaolin.

**Comment by tghim** [comment]
OK, Thank you for your reply!
